// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHSB_VHTVqiZjmJJ6lc-0yLTwZ6wrT44c',
    appId: '1:695964703599:web:643c00a17c315a0d1b269a',
    messagingSenderId: '695964703599',
    projectId: 'ease-tube',
    authDomain: 'ease-tube.firebaseapp.com',
    storageBucket: 'ease-tube.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCStlXw9L9u03UsQLg4dQf7lGIE9HiQHwo',
    appId: '1:695964703599:android:cc19bfeec63eb7101b269a',
    messagingSenderId: '695964703599',
    projectId: 'ease-tube',
    storageBucket: 'ease-tube.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHSB_VHTVqiZjmJJ6lc-0yLTwZ6wrT44c',
    appId: '1:695964703599:ios:134bde2b3cf55f051b269a',
    messagingSenderId: '695964703599',
    projectId: 'ease-tube',
    storageBucket: 'ease-tube.firebasestorage.app',
    iosBundleId: 'com.example.ease_tube',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIMEjozCzo5lI91r0qYL-qOidODk4AtmE',
    appId: '1:695964703599:ios:134bde2b3cf55f051b269a',
    messagingSenderId: '695964703599',
    projectId: 'ease-tube',
    storageBucket: 'ease-tube.firebasestorage.app',
    iosBundleId: 'com.example.easeTube',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHSB_VHTVqiZjmJJ6lc-0yLTwZ6wrT44c',
    appId: '1:695964703599:web:e2aefa4194d99a8f1b269a',
    messagingSenderId: '695964703599',
    projectId: 'ease-tube',
    authDomain: 'ease-tube.firebaseapp.com',
    storageBucket: 'ease-tube.firebasestorage.app',
  );

}