import 'package:ease_tube/configs/colors/app_colors.dart';
import 'package:ease_tube/configs/routes/routes.dart';
import 'package:ease_tube/configs/routes/routes_name.dart';
import 'package:ease_tube/firebase_options.dart';
import 'package:ease_tube/view/user_profile/user_profile_screen.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:ease_tube/view/home/home_screen.dart';
import 'package:ease_tube/view/login/login_screen.dart';
import 'package:flutter/material.dart';
import 'dependency_injection/locator.dart';

ServiceLocator dependencyInjector = ServiceLocator();

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  try {
    // Initializes Firebase with configurations generated by FlutterFire CLI
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    debugPrint("Firebase initialized successfully.");
  } catch (e) {
    // Prevents app crash if Firebase attempts to initialize multiple times during Hot Restart
    if (e.toString().contains('duplicate-app')) {
      debugPrint("Firebase already exists, using existing instance.");
    } else {
      rethrow;
    }
  }

  // Sets up GetIt or other service locators for dependency management
  dependencyInjector.servicesLocator();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      // Global theme configuration for the application
      theme: ThemeData(
        useMaterial3: true,
        // Ensures all loaders in the app use the Ease'TUBE primary brand color
        progressIndicatorTheme: const ProgressIndicatorThemeData(
          color: AppColors.primary,
        ),
      ),
      // Set to Splash to ensure branding is shown on every app launch
      initialRoute: RoutesName.splash,
      // Dynamic routing handler for complex navigation
      onGenerateRoute: Routes.generateRoute,
      // Static route map for direct navigation transitions
      routes: {
        'login_screen': (context) => const LoginScreen(),
        'home_screen': (context) => const HomeScreen(),
        'user_profile_screen': (context) => const UserProfileScreen(),
      },
    );
  }
}
